[build]
  publish = ".next"
  command = "npm run build:netlify"

[build.environment]
  # Enable Next.js optimization
  NEXT_TELEMETRY_DISABLED = "1"
  # Reduce memory usage during build
  NODE_OPTIONS = "--max-old-space-size=4096"

# Next.js plugin for Netlify (required for App Router)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function configuration for better performance
[functions]
  # Exclude large files and directories from functions
  included_files = ["!node_modules/**", "!.next/cache/**", "!public/admin/**", "!scripts/**", "!*.md", "!*.txt"]

# Enhanced compression and caching
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers (from Next.js config)
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    # Performance headers
    X-DNS-Prefetch-Control = "on"

# Font files - no compression to avoid decoding issues
[[headers]]
  for = "/_next/static/media/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"
    # Explicitly disable compression for font files
    Content-Encoding = ""

[[headers]]
  for = "/_next/static/media/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff"
    Content-Encoding = ""

[[headers]]
  for = "/_next/static/media/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/ttf"
    Content-Encoding = ""

# Font files in public directory
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = ""

# Font files anywhere
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"
    Content-Encoding = ""

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff"
    Content-Encoding = ""

# Static assets caching (removed Content-Encoding to let Netlify handle compression)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript and CSS files
[[headers]]
  for = "/_next/static/chunks/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

# Image optimization caching
[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Images in static directory
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Admin CMS configuration
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

# Handle Next.js routing (removed - @netlify/plugin-nextjs handles this automatically)
# Note: Next.js App Router routing is handled by the Netlify Next.js plugin

# Redirects for specific routes (if needed)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Ensure no compression is applied to any font files
[[headers]]
  for = "**/fonts/**"
  [headers.values]
    Content-Encoding = ""

[[headers]]
  for = "**/*font*"
  [headers.values]
    Content-Encoding = ""

# Edge Functions for enhanced performance (optional)
# [[edge_functions]]
#   function = "geo-headers"
#   path = "/*"

# Netlify asset optimization settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
