backend:
  name: test-repo

media_folder: "public/images" 
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      
  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Short Description", name: "shortDescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "press"
    label: "Press"
    folder: "src/content/press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Source", name: "source", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "External Link", name: "link", widget: "string", required: false}

  - name: "career"
    label: "Career"
    folder: "src/content/career"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Short Description", name: "shortDescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "acceleration"
    label: "Acceleration"
    folder: "src/content/acceleration"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Short Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "news"
    label: "News"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Button Text", name: "buttonText", widget: "string"}
      - {label: "Variant", name: "variant", widget: "select", options: ["right", "left"], default: "right"}

  - name: "faq"
    label: "FAQ"
    folder: "src/content/faq"
    create: true
    slug: "{{slug}}" # or "{{question_slug}}" if you want slugs based on question
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order of the FAQ item. Lower numbers appear first."}
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Answer", name: "answer", widget: "markdown"}

  - name: "quotes"
    label: "Quotes"
    folder: "src/content/quotes"
    create: true
    slug: "{{slug}}" # or "{{name_slug}}" if you want slugs based on person's name
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Image", name: "imageSrc", widget: "image"}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}" # or "{{sitename_slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", value_type: "int", hint: "Enter a number to define the display order. Lower numbers appear first."}
      - {label: "Variant", name: "variant", widget: "select", options: ["big", "small"], default: "big", hint: "Select the card size variant."}
      - {label: "Image", name: "imageSrc", widget: "image", hint: "Upload the project image."}
      - {label: "Alt Text", name: "alt", widget: "string", hint: "Enter descriptive alt text for the image."}
      - {label: "Site Name", name: "siteName", widget: "string", hint: "Enter the name of the project/site."}
      - {label: "Description", name: "description", widget: "markdown", hint: "Enter a detailed description of the project."}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "Enter tags related to the project."}
      - {label: "Link", name: "link", widget: "string", required: false, hint: "Enter an optional external link for the project."}